services:
  api-gateway:
    build:
      context: ../api-gateway
    container_name: api-gateway-service
    ports:
      - "8080:8080"
    environment:
      - AUTH_SERVICE_URL=http://auth-service:8081
    networks:
      - bido-network
    restart: unless-stopped

  postgres-db:
    image: postgres:18
    container_name: postgres-db-server
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: postgres
    networks:
      - bido-network
    volumes:
      - ../bido-resources/database/users:/docker-entrypoint-initdb.d
    restart: unless-stopped

  auth:
    build:
      context: ../auth
    container_name: auth-service
    expose:
      - "8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db-server:5432/auth_db
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
    networks:
      - bido-network
    restart: unless-stopped
    depends_on:
      - postgres-db

networks:
  bido-network:
